model_type: res18_linear
data_type: classify
save_prefix: 0821_infe
note: Use manual label in 2022 & hengfa to pretrain the model. Channel = 3. Combine sink and stand as still.

train_list: ''
val_list: ./data_process/trainlist_0821_infe/0821_infe.txt
gpus: [1]
load_model_path: './checkpoints/eval_model/optimal.pth' #res18_linear_pre_resnet18_split_1_3_aug_recaug/latest.pth'res18_linear_pre_resnet18_split_rec_1_2_2cls_nofloat  res18_linear_pre_resnet18_split_1_3_aug_recaug_new res18_linear_pre_resnet18_split_1_2_aug #res18_linear_pre_resnet18_split_1_2_train_norec Your pretrained model path
load_not_strict: false  # When you use pretrained model, set it true if your model has difference with load model
seed: 42

num_classes: 2
channel_num: 3
wandb_sweep_path: ''    # If you want to use wandb sweep, a config file is required
train: false             # If false, load_model_path is required

lr: 1e-3
lr_decay_epochs: [150, 275, 400]
lr_decay_rate: 0.1
weight_decay: 1e-4
momentum: 0.9
beta: 0.999
cosine: true
warm: true             # change
loss: ce
temperature: 0.07
model_dir: ''           # If it's empty, it can be auto generated
freeze_layers: []
# freeze_layers: ['conv1', 'layer1', 'layer2']

batch_size: 1
epochs: 100
augment_type: 'none'
print_freq: 10

vis_freq: 10
result_dir: ''          # If it's empty, it can be auto generated

label2id: {
  "stand": 0,
  "struggle": 1,
  "float": 1,
  "sinking": -1,
  "sink": -1,
  "swim": 1,
  "others": -1,
  "other": -1,
  "noise": -1,
  "abnormal": -1,
  "none": 1,
  "moving": 1,
}
